services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app # Comment this line if you want to use a pre-built image instead of building from source
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:latest
    env_file:
      - database.env
    ports: # Uncomment if you want to expose the database port
    - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports: # Uncomment if you want to expose the Redis port
      - "6379:6379"


volumes:
  postgres-data:
